# Generated by Django 3.1.1 on 2020-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=64)),
                ('department_timing', models.IntegerField()),
                ('department_branch', models.ManyToManyField(related_name='departs', to='employee_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fname', models.CharField(max_length=30)),
                ('employee_lname', models.CharField(max_length=30)),
                ('employee_add', models.CharField(max_length=20)),
                ('employee_dept', models.ManyToManyField(related_name='workers', to='employee_app.departments')),
            ],
        ),
    ]
